name: Filzer
options:
  bundleIdPrefix: com.guy
  deploymentTarget:
    iOS: "15.0"

packages:
  PartyUI:
    url: https://github.com/jailbreakdotparty/PartyUI.git
    from: 1.2.1

targets:
  Filzer:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources
    dependencies:
      - package: PartyUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.guy.filzer
        INFOPLIST_FILE: Resources/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"

fileGroups:
  - Resources
